name: CI

on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        ruby-version: [ '2.6', '2.7', '3.0', '3.1' ]
        gemfile:
          - gemfiles/rails-5.2.gemfile
          - gemfiles/rails-6.0.gemfile
          - gemfiles/rails-6.1.gemfile
          - gemfiles/rails-7.0.gemfile
        exclude:
          - ruby-version: '3.1'
            gemfile: rails_5_2
          - ruby-version: '3.0'
            gemfile: rails_5_2
          # rails 7.x requires ruby >= 2.7.0
          - ruby-version: '2.6'
            gemfile: rails_7_0
        include:
          # test latest rails and ruby
          - ruby-version: ruby-head
            gemfile: gemfiles/rails-main.gemfile

    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v1

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rake
